baseURL = "https://roman-gardens.github.io/"
relativeURLs = false

languageCode = "en-us"
title = "Gardens of the Roman Empire"
theme = "mainroad"
paginate = "1000"

publishDir = "docs"

buildDrafts = false
enableEmoji = true
enableInlineShortcodes = true

summaryLength = 10000

[menu]

	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/home/"
		weight = -130

	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = -120

	[[menu.main]]
		identifier = "gardens"
		name = "Gardens"
		url = "/province/"
		weight = -110

	[[menu.main]]
		identifier = "contributors"
		name = "People"
		url = "/contributors/"
		weight = -100

	[[menu.main]]
		identifier = "contribute"
		name = "Join"
		url = "/contribute/"
		weight = -90

	[[menu.main]]
		identifier = "blog"
		name = "News"
		url = "/blog/"
		weight = -80

	[[menu.main]]
		identifier = "citation"
		name = "How to Cite"
		url = "/citation/"
		weight = -70


[Params]
twitter_cards = true
images = ["images/landing-page-map-1.png"]
customCSS = ["css/custom.css"]
highlightColor = "#c22d30"

[Params.logo]
title = "GARDENS of the ROMAN EMPIRE"

[Params.sidebar]
	home = "left" # Configure layout for home page
	list = "left"  # Configure layout for list pages
	single = "left" # Configure layout for single pages
	# Enable widgets in given order
	# widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
	widgets = ["search-lunr", "map", "taglist"]

[Params.widgets]
	recent_num = 2 # Set the number of articles in the "Recent articles" widget
	tags_counter = true # Enable counter for each tag in "Tags" widget
