name: publish to test-b website repo

on:
  workflow_dispatch:
    branches:
      - main  # User can select branch to deploy when running

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify --baseURL "https://roman-gardens.github.io/test-b/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_TEST_B }}
          external_repository: roman-gardens/test-b
          publish_branch: main
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}
