name: publish to gre-website-test

on:
  workflow_dispatch:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify --baseURL "https://roman-gardens.github.io/gre-website-test/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY_TEST }}
          EXTERNAL_REPOSITORY: roman-gardens/gre-website-test
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./docs
        with:
          emptyCommits: false
          commitMessage: ${{ github.event.head_commit.message }}
