name: publish to roman-gardens.github.io

on:
  workflow_dispatch:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false # no longer using submodules
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: roman-gardens/roman-gardens.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./docs
        with:
          emptyCommits: false
          commitMessage: ${{ github.event.head_commit.message }}
